# Generated by Django 6.0.3 on 2026-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
