# Generated by Django 6.0.3 on 2026-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_libro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, default='No especificado', max_length=50, null=True),
        ),
    ]
